server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id : donation
          uri: http://localhost:8010
          predicates:
            - Path=/api/donation/**
        - id: volunteering
          uri: http://localhost:8020
          predicates:
            - Path=/api/volunteering/**
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8080/realms/spring-boot-microservices-project

